### ISSUE TITLE
handle meridian flips between dithers exposures

### ISSUE THREAD

**Issue by lspitler** [AstroHuntsman/huntsman-pocs#10]

**Comment by AnthonyHorton** [comment]
Is this a symptom of a more general issue, i.e. not checking mount state before starting any exposure (not just the first in an observing block)?

**Comment by AnthonyHorton** [comment]
For Huntsman we need to ensure we check both mount & dome state before starting any & all exposures (apart from darks), i.e. need to check to the dome has completed a slew as well as the mount.

**Comment by lspitler** [comment]
@danjampro and I think this is done...
