### ISSUE TITLE
come up with twilight plan

### ISSUE THREAD

**Issue by lspitler** [AstroHuntsman/huntsman-pocs#16]
- turn on cameras, etc
- open dome at sunset if clear weather
- home mount
- dome flat?
- twilight flat narrow band
- coarse focus narrow band
- twilight flat broad band
- coarse focus narrow band
- fine focus sequence?
- PSF star? photometric field?
- slew to first target

**Comment by wtgee** [comment]
Note that we have cameras hard-coded right now, which will need to work with the filter management system.

https://github.com/AstroHuntsman/huntsman-pocs/blob/develop/states/huntsman/calibrating.py#L23

**Comment by AnthonyHorton** [comment]
The state machine can use the cameras' `filter_type` and/or autofocus exposure time attributes to decide when in twilight to do its flats. Ultimately the filter management system should be setting both of those via the config file.

**Comment by AnthonyHorton** [comment]
Also, coarse focus should hardly ever be required. Once we have found a good focus for a particular lens, filter & camera combo we should be able to use the last known good focus value as a starting point for a fine focus.
