### ISSUE TITLE
WCS information only goes into the file for the camera marked as "primary"

### ISSUE THREAD

**Issue by lspitler** [AstroHuntsman/huntsman-pocs#22]
It should go into all files.

**Comment by wtgee** [comment]
We want to solve them all separately? Does this need to be done while running or can it be done during a cleanup of observations as part of going into pipeline?

**Comment by lspitler** [comment]
I guess it can be done by metahunter if it is going to delay POCS, etc. Unless POCS continues while solve-field is doing its thing?

**Comment by AnthonyHorton** [comment]
@wtgee Yes, they all need to be solved separately. Each camera will be slightly offset & rotated from the others, slightly different distortion, etc. & we need sub-pixel accuracy WCS to rebin all the images onto a common pixel grid to combine them.

metahunter is a reasonable place to do the non-primary imagers though. metahunter can just check whether each file has a valid WCS, & if not do a solve.

**Comment by lspitler** [comment]
done?
