### ISSUE TITLE
Update flat-field routine

### ISSUE THREAD

**Issue by wtgee** [AstroHuntsman/huntsman-pocs#57]
- [x] Properly enter calibrating state at correct time
- [x] Rename bias and dark files to have obvious name
- [x] Check edge cases on loops so we don't have extra dark exposures
- [x] Add morning flat procedure
- [ ] Don't save saturated flats (don't take corresponding darks for them either)
 -[ ] Figure out how to make sure it is focused before we start flats - could focus on a super-bright star?

@fergusL please directly edit list above if there is something else that needs to be done.

**Comment by lspitler** [comment]
closing, but adding remaining task to #235
